language: clojure
jdk:
  - oraclejdk8
install:
  - wget -O boot https://github.com/boot-clj/boot/releases/download/2.0.0-rc14/boot.sh
  - chmod 755 boot
  - ./boot -V
  - ./boot checkout
script:
  - ./boot test
